// <auto-generated />
using System;
using Coflnet.Sky.Referral.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SkyReferral.Migrations
{
    [DbContext(typeof(ReferralDbContext))]
    [Migration("20260831081853_CreatorOnboarding")]
    partial class CreatorOnboarding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Coflnet.Sky.Referral.Models.CreatorOnboardingReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CapacityJurisdiction")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<int>("CapacityStatus")
                        .HasColumnType("int");

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("EvidenceSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("MinecraftUuid")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("PreviousReviewId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PrivacyNoticeVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime?>("RepresentativeAcceptedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RepresentativeAccountId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("RepresentativeAgreementHash")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ResidenceCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime>("ReviewedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("SellerType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TaxDocumentRoute")
                        .HasColumnType("int");

                    b.Property<string>("TaxResidenceCountry")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)");

                    b.Property<DateTime?>("ValidUntilUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VerificationReference")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId", "PreviousReviewId")
                        .IsUnique();

                    b.HasIndex("CreatorUserId", "ReviewedAtUtc");

                    b.ToTable("CreatorOnboardingReviews", null, t =>
                        {
                            t.HasCheckConstraint("CK_CreatorOnboardingReviews_CapacityStatus", "`CapacityStatus` BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_CreatorOnboardingReviews_SellerType", "`SellerType` BETWEEN 1 AND 2");

                            t.HasCheckConstraint("CK_CreatorOnboardingReviews_Status", "`Status` BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_CreatorOnboardingReviews_TaxDocumentRoute", "`TaxDocumentRoute` BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("Coflnet.Sky.Referral.Models.ReferralElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Flags")
                        .HasColumnType("int");

                    b.Property<string>("Invited")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Inviter")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Locale")
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("ProgramVersion")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("PurchaseAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Invited")
                        .IsUnique();

                    b.HasIndex("Inviter");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("Coflnet.Sky.Referral.Models.RewardLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClaimCodeHash")
                        .IsConcurrencyToken()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("DetailsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("OfferVersion")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<long?>("PayoutThresholdEurCents")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<Guid?>("RelatedEntryId")
                        .HasColumnType("char(36)");

                    b.Property<long>("RemunerationEurCents")
                        .HasColumnType("bigint");

                    b.Property<string>("RewardAccountId")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("Source")
                        .HasColumnType("int");

                    b.Property<bool>("WasAnonymous")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimCodeHash")
                        .IsUnique();

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("RelatedEntryId");

                    b.HasIndex("RewardAccountId", "CreatedAt");

                    b.ToTable("RewardLedger", null, t =>
                        {
                            t.HasCheckConstraint("CK_RewardLedger_Claim", "(NOT `WasAnonymous` AND `RewardAccountId` IS NOT NULL AND `ClaimCodeHash` IS NULL AND `ClaimedAt` IS NULL) OR (`WasAnonymous` AND ((`RewardAccountId` IS NULL AND `ClaimCodeHash` IS NOT NULL AND `ClaimedAt` IS NULL) OR (`RewardAccountId` IS NOT NULL AND `ClaimCodeHash` IS NULL AND `ClaimedAt` IS NOT NULL)))");

                            t.HasCheckConstraint("CK_RewardLedger_Kind", "`Kind` BETWEEN 1 AND 6");

                            t.HasCheckConstraint("CK_RewardLedger_Source", "`Source` IS NULL OR `Source` BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("Coflnet.Sky.Referral.Models.RewardLedgerEntry", b =>
                {
                    b.HasOne("Coflnet.Sky.Referral.Models.RewardLedgerEntry", null)
                        .WithMany()
                        .HasForeignKey("RelatedEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
